server:
  port: 8081
  servlet:
    context-path: /kafka


spring:
  kafka:
    bootstrap-servers: 192.168.81.72:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      group-id: test-consumer-group
      auto-offset-reset: earliest


